CREATE TABLE IF NOT EXISTS aziende (id TEXT PRIMARY KEY, denominazione TEXT, licenza_scadenza TEXT, attiva INTEGER DEFAULT 1, note TEXT, moduli TEXT, prezzo_imponibile TEXT, prezzo_finale TEXT, reseller_id TEXT, creata_il TEXT DEFAULT (datetime('now')));
CREATE TABLE IF NOT EXISTS utenti (id TEXT PRIMARY KEY, email TEXT UNIQUE NOT NULL, password_hash TEXT NOT NULL, ruolo TEXT NOT NULL DEFAULT 'azienda', azienda_id TEXT, nome TEXT, staff_id TEXT, reseller_parent TEXT, creato_il TEXT DEFAULT (datetime('now')));
CREATE TABLE IF NOT EXISTS sessioni (token TEXT PRIMARY KEY, utente_id TEXT NOT NULL, scadenza TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS dati_app (id TEXT PRIMARY KEY, azienda_id TEXT NOT NULL, collezione TEXT NOT NULL, dati TEXT NOT NULL, aggiornato_il TEXT DEFAULT (datetime('now')));
CREATE TABLE IF NOT EXISTS rivenditori (id TEXT PRIMARY KEY, ragione_sociale TEXT, piva TEXT, codice_fiscale TEXT, indirizzo TEXT, cap TEXT, citta TEXT, provincia TEXT, sdi TEXT, pec TEXT, email TEXT, telefono TEXT, note TEXT, licenza_scadenza TEXT, attiva INTEGER DEFAULT 1, sconto INTEGER DEFAULT 50, creato_il TEXT DEFAULT (datetime('now')));
CREATE TABLE IF NOT EXISTS licenze_eventi (id TEXT PRIMARY KEY, azienda_id TEXT, reseller_id TEXT, tipo TEXT, mesi INTEGER, prezzo_imponibile TEXT, prezzo_finale TEXT, fatturato INTEGER DEFAULT 0, fatturato_il TEXT, creato_il TEXT DEFAULT (datetime('now')));
CREATE INDEX IF NOT EXISTS idx_dati_azienda ON dati_app(azienda_id, collezione);
CREATE INDEX IF NOT EXISTS idx_utenti_azienda ON utenti(azienda_id);
CREATE INDEX IF NOT EXISTS idx_aziende_reseller ON aziende(reseller_id);
CREATE INDEX IF NOT EXISTS idx_eventi_reseller ON licenze_eventi(reseller_id, creato_il);
